// Mocks generated by Mockito 5.4.4 from annotations
// in mtg_picker/test/ui/controllers/filter_bottom_sheet_controller/filter_bottom_sheet_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:mtg_picker/domain/enums/mana_color.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIterator_0<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Set].
///
/// See the documentation for Mockito's code generation for more information.
class MockSet extends _i1.Mock implements Set<_i2.ManaColor> {
  @override
  Iterator<_i2.ManaColor> get iterator => (super.noSuchMethod(
        Invocation.getter(#iterator),
        returnValue: _FakeIterator_0<_i2.ManaColor>(
          this,
          Invocation.getter(#iterator),
        ),
        returnValueForMissingStub: _FakeIterator_0<_i2.ManaColor>(
          this,
          Invocation.getter(#iterator),
        ),
      ) as Iterator<_i2.ManaColor>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.ManaColor get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  _i2.ManaColor get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  _i2.ManaColor get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  Set<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: <R>{},
        returnValueForMissingStub: <R>{},
      ) as Set<R>);

  @override
  bool contains(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [value],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool add(_i2.ManaColor? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addAll(Iterable<_i2.ManaColor>? elements) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [elements],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [value],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void removeAll(Iterable<Object?>? elements) => super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [elements],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainAll(Iterable<Object?>? elements) => super.noSuchMethod(
        Invocation.method(
          #retainAll,
          [elements],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWhere(bool Function(_i2.ManaColor)? test) => super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i2.ManaColor)? test) => super.noSuchMethod(
        Invocation.method(
          #retainWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool containsAll(Iterable<Object?>? other) => (super.noSuchMethod(
        Invocation.method(
          #containsAll,
          [other],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Set<_i2.ManaColor> intersection(Set<Object?>? other) => (super.noSuchMethod(
        Invocation.method(
          #intersection,
          [other],
        ),
        returnValue: <_i2.ManaColor>{},
        returnValueForMissingStub: <_i2.ManaColor>{},
      ) as Set<_i2.ManaColor>);

  @override
  Set<_i2.ManaColor> union(Set<_i2.ManaColor>? other) => (super.noSuchMethod(
        Invocation.method(
          #union,
          [other],
        ),
        returnValue: <_i2.ManaColor>{},
        returnValueForMissingStub: <_i2.ManaColor>{},
      ) as Set<_i2.ManaColor>);

  @override
  Set<_i2.ManaColor> difference(Set<Object?>? other) => (super.noSuchMethod(
        Invocation.method(
          #difference,
          [other],
        ),
        returnValue: <_i2.ManaColor>{},
        returnValueForMissingStub: <_i2.ManaColor>{},
      ) as Set<_i2.ManaColor>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Set<_i2.ManaColor> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: <_i2.ManaColor>{},
        returnValueForMissingStub: <_i2.ManaColor>{},
      ) as Set<_i2.ManaColor>);

  @override
  Iterable<_i2.ManaColor> followedBy(Iterable<_i2.ManaColor>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #followedBy,
          [other],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  Iterable<T> map<T>(T Function(_i2.ManaColor)? toElement) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [toElement],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<_i2.ManaColor> where(bool Function(_i2.ManaColor)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  Iterable<T> whereType<T>() => (super.noSuchMethod(
        Invocation.method(
          #whereType,
          [],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i2.ManaColor)? toElements) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [toElements],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  void forEach(void Function(_i2.ManaColor)? action) => super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ManaColor reduce(
          _i2.ManaColor Function(
            _i2.ManaColor,
            _i2.ManaColor,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  T fold<T>(
    T? initialValue,
    T Function(
      T,
      _i2.ManaColor,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i3.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as T);

  @override
  bool every(bool Function(_i2.ManaColor)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
      ) as String);

  @override
  bool any(bool Function(_i2.ManaColor)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i2.ManaColor> toList({bool? growable = true}) => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
          {#growable: growable},
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as List<_i2.ManaColor>);

  @override
  Iterable<_i2.ManaColor> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  Iterable<_i2.ManaColor> takeWhile(bool Function(_i2.ManaColor)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  Iterable<_i2.ManaColor> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  Iterable<_i2.ManaColor> skipWhile(bool Function(_i2.ManaColor)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: <_i2.ManaColor>[],
        returnValueForMissingStub: <_i2.ManaColor>[],
      ) as Iterable<_i2.ManaColor>);

  @override
  _i2.ManaColor firstWhere(
    bool Function(_i2.ManaColor)? test, {
    _i2.ManaColor Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  _i2.ManaColor lastWhere(
    bool Function(_i2.ManaColor)? test, {
    _i2.ManaColor Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  _i2.ManaColor singleWhere(
    bool Function(_i2.ManaColor)? test, {
    _i2.ManaColor Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);

  @override
  _i2.ManaColor elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _i2.ManaColor.manaWhite,
        returnValueForMissingStub: _i2.ManaColor.manaWhite,
      ) as _i2.ManaColor);
}
